// ここにサイトやツールを追加していくよ！
// category: "game" | "tool" | "useful" | "event" | "other"
// zip: { url: "ファイルパス", label: "ダウンロード名" } を付けるとダウンロードボタンが出るよ
//
// フォルダの中にさらにフォルダ（サブフォルダ）を作りたいときは
// group / groupMeta を付ける。同じ group の項目がまとまって
// 中カテゴリになり、section で見出しごとに分けられる。
const SITE_DATA = [
  // ==== イベント：O中からの脱出（謎解き 全リンク集） ====
  {
    category: "event",
    group: "oichu-escape",
    groupMeta: { label: "O中からの脱出", emoji: "🚪", color: "#FF9F5A" },
    section: "参加者に渡すもの",
    title: "手紙ページ（みんなで見る用）",
    description: "参加者全員で見る導入の手紙ページ。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/letter.html?replay=1",
    emoji: "💌",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "参加者に渡すもの",
    title: "ルートA 入口QR",
    description: "ルートAのスタート地点に貼るQR用リンク。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/index.html?skip=1&route=A",
    emoji: "🅰️",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "参加者に渡すもの",
    title: "ルートB 入口QR",
    description: "ルートBのスタート地点に貼るQR用リンク。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/index.html?skip=1&route=B",
    emoji: "🅱️",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "参加者に渡すもの",
    title: "復活呪文（先生が唱える用）",
    description: "詰まった参加者を復活させるための先生用ページ。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/revive.html",
    emoji: "🧙",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "運営用",
    title: "デバッグ（好きな場所にスキップ）",
    description: "動作確認用。任意の地点にスキップできる運営専用ページ。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/index.html?debug=1",
    emoji: "🛠️",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "運営用",
    title: "ダッシュボード",
    description: "進行状況などを確認する運営用ダッシュボード。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/dashboard.html",
    emoji: "📊",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "各謎（QRに埋め込む用）",
    title: "中謎①",
    description: "QR設置用：中謎1問目。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/point.html?p=1",
    emoji: "🧩",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "各謎（QRに埋め込む用）",
    title: "中謎②",
    description: "QR設置用：中謎2問目。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/point.html?p=2",
    emoji: "🧩",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "各謎（QRに埋め込む用）",
    title: "中謎③",
    description: "QR設置用：中謎3問目。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/point.html?p=3",
    emoji: "🧩",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "各謎（QRに埋め込む用）",
    title: "中謎④",
    description: "QR設置用：中謎4問目。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/point.html?p=4",
    emoji: "🧩",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "各謎（QRに埋め込む用）",
    title: "中謎⑤",
    description: "QR設置用：中謎5問目。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/point.html?p=5",
    emoji: "🧩",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "各謎（QRに埋め込む用）",
    title: "ジャンプ謎1",
    description: "QR設置用：ジャンプ謎1問目。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/dummy.html?d=1",
    emoji: "🦘",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "各謎（QRに埋め込む用）",
    title: "ジャンプ謎2",
    description: "QR設置用：ジャンプ謎2問目。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/dummy.html?d=2",
    emoji: "🦘",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "各謎（QRに埋め込む用）",
    title: "ジャンプ謎3",
    description: "QR設置用：ジャンプ謎3問目。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/dummy.html?d=3",
    emoji: "🦘",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "参考（直接配布はしない・ゲーム内導線でたどり着く）",
    title: "扉の謎",
    description: "ゲーム内の導線からたどり着く扉の謎ページ。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/final.html",
    emoji: "🚪",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "参考（直接配布はしない・ゲーム内導線でたどり着く）",
    title: "最後の謎",
    description: "ゲーム内の導線からたどり着く最終問題ページ。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/secret.html",
    emoji: "🔮",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "参考（直接配布はしない・ゲーム内導線でたどり着く）",
    title: "完全制覇の証",
    description: "全問クリアした参加者だけが見られる証ページ。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/complete.html",
    emoji: "🏆",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "参考（直接配布はしない・ゲーム内導線でたどり着く）",
    title: "ジャンプ謎QR読み取り",
    description: "参加者がゲーム内からQRを読み取るためのページ。",
    url: "https://gamigamiigami.github.io/ManabiMatsuri/scan.html",
    emoji: "📷",
  },
  {
    category: "event",
    group: "oichu-escape",
    section: "関連ファイル",
    title: "O中からの脱出 一式DL",
    description: "関連ファイルを一括ダウンロードできるZIP。",
    url: "https://github.com/gamigamiigami/ManabiMatsuri/archive/refs/heads/claude/handoff-docs-review-8qemhk.zip",
    emoji: "📦",
    zip: {
      url: "https://github.com/gamigamiigami/ManabiMatsuri/archive/refs/heads/claude/handoff-docs-review-8qemhk.zip",
      label: "一式ZIPをダウンロード",
    },
  },
  // ==== 教育ゲーム ====
  {
    category: "game",
    title: "品詞パニック",
    description: "品詞を見分けるスピード勝負のゲーム。",
    url: "https://gamigamiigami.github.io/Workspace/projects/hinshi-panic/",
    emoji: "🧩",
  },
  {
    category: "game",
    title: "返り点クエスト（配布用）",
    description: "返り点の読み方を冒険形式で学べるクエスト。生徒配布はこちら。",
    url: "https://gamigamiigami.github.io/Workspace/kaeriten-quest/",
    emoji: "↩️",
    tags: ["旧URL・生徒配布用"],
  },
  {
    category: "game",
    title: "返り点クエスト（新URL）",
    description: "返り点クエストの新しい設置先。今後はこちらに統一予定。",
    url: "https://gamigamiigami.github.io/Workspace/projects/kaeriten-quest/",
    emoji: "↩️",
    tags: ["新URL"],
  },
  {
    category: "game",
    title: "計算クエスト",
    description: "計算問題を解きながら進むクエスト形式のゲーム。",
    url: "https://gamigamiigami.github.io/Workspace/projects/keisan-quest/",
    emoji: "🔢",
  },
  {
    category: "game",
    title: "gamedata ver2",
    description: "ゲーム用データまわりのページ。",
    url: "https://gamigamiigami.github.io/gamedata/ver2/",
    emoji: "🗂️",
  },
  {
    category: "game",
    title: "あいうえおすごろく",
    description: "あいうえおを楽しく学べるすごろくゲーム。",
    url: "https://aiue-sugoroku.netlify.app/",
    emoji: "🎲",
  },
  // ==== その他ゲーム ====
  {
    category: "othergame",
    title: "オシキング",
    description: "オシキングで遊べるゲーム。",
    url: "https://gamigamiigami.github.io/Workspace/projects/oshiking/",
    emoji: "👑",
  },
  {
    category: "othergame",
    title: "io games",
    description: "ブラウザで遊べるioゲーム。",
    url: "https://iogames91531.netlify.app",
    emoji: "🕹️",
  },
  {
    category: "othergame",
    title: "Toy Mania",
    description: "おもちゃがテーマのWebゲーム。",
    url: "https://gamigamiigami.github.io/toy-mania-web/",
    emoji: "🧸",
  },
  {
    category: "othergame",
    title: "AAA-",
    description: "ブラウザで遊べるゲーム。",
    url: "https://gamigamiigami.github.io/AAA-/",
    emoji: "🎮",
  },

  // ==== 便利ツール ====
  {
    category: "useful",
    title: "クロスワードサポーター",
    description: "クロスワード作りをサポートしてくれるツール。",
    url: "https://gamigamiigami.github.io/Workspace/projects/crossword/",
    emoji: "🔡",
  },
  {
    category: "useful",
    title: "文字替え",
    description: "文字を入れ替えて使う言葉まわりのツール。",
    url: "https://gamigamiigami.github.io/Workspace/projects/moji-kae/",
    emoji: "🔤",
  },
  {
    category: "useful",
    title: "文字ずらし",
    description: "文字をずらして使う言葉まわりのツール。",
    url: "https://gamigamiigami.github.io/Workspace/projects/moji-zurashi/",
    emoji: "🔠",
  },
  {
    category: "useful",
    title: "PDFリンくん",
    description: "PDFにリンクをつけるための説明書ツール。",
    url: "https://pdf-linkun.netlify.app/",
    emoji: "📄",
  },

  // ==== イベント ====
  {
    category: "event",
    title: "Rough（ボドゲ会）",
    description: "ボードゲーム会「Rough」の案内ページ。",
    url: "https://gamigamiigami.github.io/Workspace/projects/rough/",
    emoji: "🎲",
  },
];

const CATEGORY_META = {
  game:      { label: "教育ゲーム", emoji: "🎮", color: "#FF6FA5" },
  othergame: { label: "その他ゲーム", emoji: "🎲", color: "#B48CFF" },
  tool:      { label: "教育ツール", emoji: "📚", color: "#5EC8FF" },
  useful:    { label: "便利ツール", emoji: "🛠️", color: "#7CE38B" },
  event:  { label: "イベント",   emoji: "🎉", color: "#FFC24B" },
  other:  { label: "その他",     emoji: "✨", color: "#C79CFF" },
};
